services:
  satml-dev:
    image: satml_dev_image
    build:
      context: .
      dockerfile: dev_gpu.Dockerfile
    volumes:
      - .:/workspace/app
    working_dir: /workspace/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
